### PR TITLE
Properly handle null upsert keys

### PR DESCRIPTION
**Pull request by seamusabshere**
When you naively upsert against a column that might be null, you risk creating duplicate rows (and not updating the data you expect) because null does not equal null.

In the past, we raised an error if a table didn't enforce NOT NULL (or REQUIRED on BigQuery). This prevented people from making mistakes, but it made it very hard to use dbcrossbar against legacy tables (or with data that may contain a negligible fraction of nulls that you want to ignore).

This PR removes the NOT NULL enforcement. It also adds a subquery into the upsert MERGE statement that drops rows that have null upsert keys. This will be the desired behavior 95% of the time.

### CODE REVIEW

**Comment by emk** [comment]
> It also adds a subquery into the upsert MERGE statement that drops rows that have null upsert keys. This will be the desired behavior 95% of the time.

This means that we'd silent dropping data with no error or warning. Could you please explain why that would be a "desired behavior"?

**Comment by emk** [comment]
I think what we really need here is a test case, because otherwise it's really hard to think about the ideal behavior.

**Comment by seamusabshere** [comment]
@emk having written a million ETL jobs at this point, my desired behavior is always

* strip whitespace (including newlines)
* convert numerics to floats
* if i specify a primary key, and 0.5% of the data is missing that primary key, just drop that data

you've talked about a `--lossy` option before... i can imagine ^^ being separate options... or we could just build the tool we want to use and accept that ^ is what an ETL pro almost certainly wants

**Comment by emk** [comment]
> having written a million ETL jobs at this point

This may be a disagreement of scope. I agree that good ETL tools are important, but I believe that `dbcrossbar` should remain a simple data-moving tool with a clear purpose, and that ETL cleanup should be done using either:

1. Tools like `scrubcsv` and `falconeri` to fix CSV files before importing them, or
2. Native BigQuery SQL to clean up and `MERGE` the data once imported.

If we start adding ETL and data-cleaning features into `dbcrossbar`, there's no obvious or clear stopping point. I feel that `dbcrossbar`'s job to move data from point A to point B, with as little change and data loss as humanly possible.

`dbcrossbar` also has massively less parallelism available than either `falconeri` or BigQuery, so it's not an efficient place to munge the CSVs.

**Comment by emk** [comment]
There is now an option in `scrubcsv` which can be used to drop rows that are missing a primary key. The official recommendation for handling this problem at scale is to use:

- Use `scrubcsv --drop-row-if-null=$COL` to remove broken rows. If you need to this at cluster scale, use `falconeri` or a similar tool to distribute the job. This is _much_ more scalable than `dbcrossbar` could ever be, and it doesn't compromise `dbcrossbar`'s mission to be a dumb-but-fast data pipe.
- Use `dbcrossbar cp $SOURCE dbcrossbar-schema:-` to fetch the source schema, mark any primary key columns as mandatory, and pass the edited `--schema` when using `dbcrossbar` to import data into BigQuery.

**Pull request closed without merging**
